import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { vi } from "vitest";

export const DATA = resolve(process.cwd(), "test-data")   // generated by `npm test` (pretest); never production data;
export const haveData = existsSync(`${DATA}/latest.json`);
export const readJSON = <T>(rel: string): T => JSON.parse(readFileSync(`${DATA}/${rel}`, "utf8")) as T;

/** Serve the pipeline's real output through fetch(). `override` lets a test corrupt/omit files. */
export function stubFetch(override: Record<string, unknown | null> = {}) {
  vi.stubGlobal("fetch", async (url: string) => {
    const rel = String(url).replace(/^.*?data\//, "");
    if (rel in override) { const v = override[rel]; return v === null ? new Response("nope", { status: 404 }) : new Response(JSON.stringify(v), { status: 200 }); }
    const p = `${DATA}/${rel}`;
    return existsSync(p) ? new Response(readFileSync(p, "utf8"), { status: 200 }) : new Response("nope", { status: 404 });
  });
}

/** jsdom has no canvas/observers. Minimal, honest stubs: they record, they don't render. */
export function stubBrowser() {
  const ctx = new Proxy({}, { get: () => () => undefined, set: () => true });
  HTMLCanvasElement.prototype.getContext = (() => ctx) as never;
  vi.stubGlobal("ResizeObserver", class { observe() {} disconnect() {} unobserve() {} });
  vi.stubGlobal("IntersectionObserver", class { observe() {} disconnect() {} unobserve() {} takeRecords() { return []; } });
  vi.stubGlobal("matchMedia", (q: string) => ({ matches: false, media: q, addEventListener() {}, removeEventListener() {} }));
  vi.stubGlobal("requestAnimationFrame", () => 0);
  Element.prototype.scrollIntoView = () => {};
}
